version: 1.3.2.{build}
branches:
  only:
  - master
  - development
image: WMF 5
build: off
init:
  - ps: Install-PackageProvider NuGet -Force | Out-Null
install:
  - ps: Install-Module -Name Pester -Force
test_script:
# Test
  - ps: . .\Tests\appveyor.pester.ps1 -Test
# Finalize pass - collect and upload results
  - ps: . .\Tests\appveyor.pester.ps1 -Finalize