#
# Module manifest for module 'Brickset'
#
# Generated by: jmedd
#
# Generated on: 09/07/2015
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '1.1'

# ID used to uniquely identify this module
GUID = '79ec18d2-adb1-4599-901b-2cad30680526'

# Author of this module
Author = 'Jonathan Medd'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2015 Jonathan Medd. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Module for working with the Brickset API - http://www.brickset.com'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = 'Functions\Private\xCheckGlobalBricksetConnection.ps1'

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = 'Functions\Public\Connect-Brickset.psm1',
                'Functions\Public\Get-BricksetRecentlyUpdatedSet.psm1',
				'Functions\Public\Get-BricksetSet.psm1',
				'Functions\Public\Get-BricksetSetAdditionalImage.psm1',
				'Functions\Public\Get-BricksetSetDetailed.psm1',
				'Functions\Public\Get-BricksetSetInstructions.psm1',
				'Functions\Public\Get-BricksetSetReview.psm1',
				'Functions\Public\Get-BricksetSubtheme.psm1',
				'Functions\Public\Get-BricksetTheme.psm1',
				'Functions\Public\Get-BricksetYear.psm1',
				'Functions\Public\Test-BricksetAPIKey.psm1'

# Functions to export from this module
FunctionsToExport = @('Connect-Brickset','Get-BricksetRecentlyUpdatedSet','Get-BricksetSet','Get-BricksetSetAdditionalImage','Get-BricksetSetDetailed','Get-BricksetSetInstructions','Get-BricksetSetReview','Get-BricksetSubtheme','Get-BricksetTheme','Get-BricksetYear','Test-BricksetAPIKey')

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

